// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portions.Infrastructure.Persistence;

#nullable disable

namespace Portions.Infrastructure.Migrations
{
    [DbContext(typeof(PortionsDbContext))]
    [Migration("20230829163333_mig0")]
    partial class mig0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portions.Domain.Entities.Portion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerseText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Portions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0beea15d-a687-4a01-b53b-72bd246f141a"),
                            CreatedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(8945),
                            LastModifiedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(8990),
                            VerseText = "0beea15d-a687-4a01-b53b-72bd246f141a - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        },
                        new
                        {
                            Id = new Guid("c416e5b7-fdbb-4ee4-8d87-4101b527f895"),
                            CreatedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9054),
                            LastModifiedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9057),
                            VerseText = "c416e5b7-fdbb-4ee4-8d87-4101b527f895 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        },
                        new
                        {
                            Id = new Guid("2984a841-7df6-4500-ac7a-b89e430acd1a"),
                            CreatedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9068),
                            LastModifiedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9071),
                            VerseText = "2984a841-7df6-4500-ac7a-b89e430acd1a - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        },
                        new
                        {
                            Id = new Guid("26e53cb4-4d06-4fd9-8b52-ec3cb8e6d3b5"),
                            CreatedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9079),
                            LastModifiedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9082),
                            VerseText = "26e53cb4-4d06-4fd9-8b52-ec3cb8e6d3b5 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        },
                        new
                        {
                            Id = new Guid("9472365c-b7ce-4a05-bf86-4e514f8e00e8"),
                            CreatedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9199),
                            LastModifiedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9203),
                            VerseText = "9472365c-b7ce-4a05-bf86-4e514f8e00e8 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        },
                        new
                        {
                            Id = new Guid("c4e8ed88-28ff-4001-8df4-001dfc82d502"),
                            CreatedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9264),
                            LastModifiedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9267),
                            VerseText = "c4e8ed88-28ff-4001-8df4-001dfc82d502 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        },
                        new
                        {
                            Id = new Guid("2ee27b01-4921-4f6b-b544-1c5a1847c390"),
                            CreatedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9276),
                            LastModifiedDate = new DateTime(2023, 8, 29, 11, 33, 33, 802, DateTimeKind.Local).AddTicks(9278),
                            VerseText = "2ee27b01-4921-4f6b-b544-1c5a1847c390 - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
